backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "img"
public_folder: "img"

collections:
  - name: "loja"
    label: "Loja e Vitrine"
    files:
      - label: "Lista de Produtos"
        name: "products_list"
        file: "data/products.json"
        fields:
          - label: "Produtos"
            name: "products"
            widget: "list"
            fields:
              - {label: "ID do Produto", name: "id", widget: "string"}
              - {label: "Nome da Peça", name: "name", widget: "string"}
              - {label: "Categoria", name: "category", widget: "select", options: ["Bags", "Chokers", "Acessórios", "Custom"]}
              - {label: "Preço", name: "price", widget: "string"}
              - {label: "Foto Oficial", name: "image", widget: "image"}
              - {label: "Descrição Editorial", name: "description", widget: "text"}
              - {label: "Link do WhatsApp (Comprar)", name: "link", widget: "string"}
