backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "img"
public_folder: "img"

collections:
  - name: "loja"
    label: "Loja e Vitrine"
    files:
      - label: "Lista de Produtos"
        name: "products_list"
        file: "data/products.json"
        fields:
          - label: "Produtos"
            name: "products"
            widget: "list"
            fields:
              - {label: "ID do Produto", name: "id", widget: "string", hint: "Ex: M1, M2..."}
              - {label: "Nome da Peça", name: "name", widget: "string"}
              - {label: "Categoria", name: "category", widget: "select", options: ["Bags", "Chokers", "Acessórios", "(Encomende)"]}
              - {label: "Preço", name: "price", widget: "string", hint: "Formato: R$ 0,00"}
              - {label: "Foto de Capa (Principal)", name: "image", widget: "image"}
              - {label: "Galeria de Fotos (Até 5 extras)", name: "images", widget: "list", field: {label: "Foto Extra", name: "image", widget: "image"}}
              - {label: "Descrição Editorial", name: "description", widget: "text"}
              - {label: "Link do Instagram", name: "link", widget: "string", hint: "Link para o post ou perfil"}
